INFO : [25/Aug/2023 11:37:21 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:37:21 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : [Errno 2] No such file or directory: 'media/brand_logo/logo.jpg']
INFO : [25/Aug/2023 11:38:10 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:38:13 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:40:20 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:40:23 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:41:43 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:41:45 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:42:44 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:42:47 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:43:16 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:43:18 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:44:00 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:44:03 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:45:10 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:45:12 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:45:32 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:45:34 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : Brand matching query does not exist.]
INFO : [25/Aug/2023 11:46:27 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 11:46:31 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')], 'role': [ErrorDetail(string='Invalid pk "SUPERADMIN" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:15:59 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:16:03 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')], 'role': [ErrorDetail(string='Invalid pk "SUPERADMIN" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:18:04 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:18:08 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')], 'role': [ErrorDetail(string='Invalid pk "SUPERADMIN" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:19:14 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:19:16 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'brand_id': [ErrorDetail(string='brand with this brand id already exists.', code='unique')]}]
INFO : [25/Aug/2023 12:19:42 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:19:45 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')], 'role': [ErrorDetail(string='Invalid pk "SUPERADMIN" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:21:21 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:21:25 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')], 'role': [ErrorDetail(string='Invalid pk "SUPERADMIN" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:27:09 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:27:13 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')], 'role': [ErrorDetail(string='Invalid pk "SUPERADMIN" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:33:58 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:34:01 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : BrandRoles() got unexpected keyword arguments: 'created_st']
INFO : [25/Aug/2023 12:35:04 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:35:08 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:44:53 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
ERROR : [25/Aug/2023 12:44:58 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post --> exception : {'user': [ErrorDetail(string='Invalid pk "Sashi Das" - object does not exist.', code='does_not_exist')], 'brand': [ErrorDetail(string='Invalid pk "utsav cafe" - object does not exist.', code='does_not_exist')]}]
INFO : [25/Aug/2023 12:50:13 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
INFO : [25/Aug/2023 12:54:16 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
INFO : [25/Aug/2023 13:12:44 package : micro_brand_service.controller.brandmainController --> position : BrandCreateController.post]
INFO : [25/Aug/2023 20:15:05 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.post]
INFO : [25/Aug/2023 20:25:36 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:25:36 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : 'MainService' object has no attribute 'getAll']
INFO : [25/Aug/2023 20:26:51 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:26:52 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:26:53 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:26:54 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:26:55 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:26:55 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:27:22 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:27:23 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:27:51 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:27:52 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:27:53 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:29:33 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:29:34 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:29:35 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:38:24 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:38:25 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.]
INFO : [25/Aug/2023 20:38:41 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:38:43 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Field name `brand_logo` is not valid for model `Brand`.]
INFO : [25/Aug/2023 20:39:15 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:40:29 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:40:53 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 20:45:55 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:45:57 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `a` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'a'.]
INFO : [25/Aug/2023 20:49:07 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:49:09 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Field name `brand_roles_id` is not valid for model `BrandRoles`.]
INFO : [25/Aug/2023 20:50:20 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:50:22 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Field name `role,created_at` is not valid for model `BrandRoles`.]
INFO : [25/Aug/2023 20:50:41 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:50:43 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'user_brand_role'.]
INFO : [25/Aug/2023 20:51:18 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:51:20 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandRoles` instance.
Original exception text was: 'BrandRoles' object has no attribute 'user_brand_role'.]
INFO : [25/Aug/2023 20:51:41 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:51:43 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Field name `brand_roles_id` is not valid for model `BrandRoles`.]
INFO : [25/Aug/2023 20:52:00 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:52:02 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandRoles` instance.
Original exception text was: 'BrandRoles' object has no attribute 'user_brand_role'.]
INFO : [25/Aug/2023 20:52:21 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:52:23 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandRoles` instance.
Original exception text was: 'BrandRoles' object has no attribute 'user_brand_role'.]
INFO : [25/Aug/2023 20:53:13 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:53:15 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : 'Vendor' object is not iterable]
INFO : [25/Aug/2023 20:53:34 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:53:36 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : 'Brand' object is not iterable]
INFO : [25/Aug/2023 20:56:55 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:56:57 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : 'Brand' object is not iterable]
INFO : [25/Aug/2023 20:59:01 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 20:59:03 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : The `fields` option must be a list or tuple or "__all__". Got str.]
INFO : [25/Aug/2023 21:01:43 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:02:31 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:02:33 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:05:06 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:05:08 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:08:35 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:08:38 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:09:35 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:09:37 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:12:07 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:12:09 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:13:14 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:13:16 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:14:25 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:17:12 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:17:14 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Field name `govt_doc` is not valid for model `BrandVerification`.]
INFO : [25/Aug/2023 21:18:01 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:18:06 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_verify` on serializer `BrandVerificationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandVerification` instance.
Original exception text was: 'BrandVerification' object has no attribute 'user_brand_verify'.]
INFO : [25/Aug/2023 21:18:26 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:18:29 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : 'Vendor' object is not iterable]
INFO : [25/Aug/2023 21:18:39 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:19:06 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:19:36 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:21:43 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:22:06 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:22:09 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_verify` on serializer `BrandVerificationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandVerification` instance.
Original exception text was: 'BrandVerification' object has no attribute 'user_brand_verify'.]
INFO : [25/Aug/2023 21:22:52 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:22:55 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_verify` on serializer `BrandVerificationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandVerification` instance.
Original exception text was: 'BrandVerification' object has no attribute 'user_brand_verify'.]
INFO : [25/Aug/2023 21:23:37 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:25:01 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:25:04 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_verify` on serializer `BrandVerificationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandVerification` instance.
Original exception text was: 'BrandVerification' object has no attribute 'user_brand_verify'.]
INFO : [25/Aug/2023 21:26:04 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:26:08 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_verify` on serializer `BrandVerificationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandVerification` instance.
Original exception text was: 'BrandVerification' object has no attribute 'user_brand_verify'.]
INFO : [25/Aug/2023 21:26:29 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:26:32 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `user_brand_verify` on serializer `BrandVerificationSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BrandVerification` instance.
Original exception text was: 'BrandVerification' object has no attribute 'user_brand_verify'.]
INFO : [25/Aug/2023 21:26:47 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:27:50 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:28:36 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:29:39 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:35:55 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:37:28 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:37:30 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:38:58 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:39:00 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:39:21 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:42:02 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:42:04 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Got AttributeError when attempting to get a value for field `brand_role` on serializer `BrandGetAllSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Brand` instance.
Original exception text was: 'Brand' object has no attribute 'brand_role'.]
INFO : [25/Aug/2023 21:44:31 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [25/Aug/2023 21:47:11 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [25/Aug/2023 21:47:13 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : It is redundant to specify `source='brand_role'` on field 'ListSerializer' in serializer 'BrandGetAllSerializer', because it is the same as the field name. Remove the `source` keyword argument.]
INFO : [25/Aug/2023 21:47:51 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
