INFO : [26/Aug/2023 08:01:56 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [26/Aug/2023 08:03:32 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
ERROR : [26/Aug/2023 08:03:32 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get --> exception : Cannot resolve keyword 'brand_role_id' into field. Choices are: brand, brand_id, created_at, id, role, role_id, user, user_id]
INFO : [26/Aug/2023 08:03:56 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [26/Aug/2023 08:04:37 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [26/Aug/2023 08:05:50 package : micro_brand_service.controller.brandcreateController --> position : BrandCreateController.get]
INFO : [26/Aug/2023 08:12:06 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:23:38 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:32:08 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:33:10 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:46:20 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:47:58 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:49:32 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 08:51:52 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 08:51:52 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() missing 2 required positional arguments: 'self' and 'request']
INFO : [26/Aug/2023 08:51:52 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 08:51:52 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() missing 2 required positional arguments: 'self' and 'request']
INFO : [26/Aug/2023 08:52:21 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 08:52:21 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() missing 1 required positional argument: 'request']
INFO : [26/Aug/2023 08:52:30 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 08:52:30 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() missing 2 required positional arguments: 'self' and 'request']
INFO : [26/Aug/2023 08:52:30 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 08:52:30 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() missing 2 required positional arguments: 'self' and 'request']
INFO : [26/Aug/2023 08:52:45 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:16:34 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:16:39 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:17:20 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:17:26 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:17:40 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:17:52 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:18:28 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:19:49 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:20:59 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 09:20:59 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() takes 2 positional arguments but 3 were given]
INFO : [26/Aug/2023 09:21:01 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 09:21:01 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() takes 2 positional arguments but 3 were given]
INFO : [26/Aug/2023 09:21:27 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 09:21:27 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : get() takes 2 positional arguments but 3 were given]
INFO : [26/Aug/2023 09:21:43 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:24:28 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:26:12 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
ERROR : [26/Aug/2023 09:26:12 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get --> exception : 'Request' object has no attribute 'split']
INFO : [26/Aug/2023 09:26:31 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:28:06 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:28:20 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.post]
INFO : [26/Aug/2023 09:29:13 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:29:56 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 09:34:51 package : micro_brand_service.controller.brandmainController --> position : BrandMainController.get]
INFO : [26/Aug/2023 10:59:37 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 10:59:37 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 1 validation error for OtpDTO
otp
  Field required [type=missing, input_value={'verifiable_cred': '8392...', 'cred_type': 'phone'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.2/v/missing]
INFO : [26/Aug/2023 11:00:09 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:00:09 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 1 validation error for OtpDTO
otp
  Field required [type=missing, input_value={'verifiable_cred': '8392...', 'cred_type': 'phone'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.2/v/missing]
INFO : [26/Aug/2023 11:01:24 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:01:24 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 1 validation error for OtpDTO
otp
  Field required [type=missing, input_value={'verifiable_cred': '8392...', 'cred_type': 'phone'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.2/v/missing]
INFO : [26/Aug/2023 11:02:55 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:02:55 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 1 validation error for OtpDTO
otp
  Field required [type=missing, input_value={'verifiable_cred': '8392...', 'cred_type': 'phone'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.2/v/missing]
INFO : [26/Aug/2023 11:03:33 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:03:33 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 'dict' object is not callable]
INFO : [26/Aug/2023 11:04:34 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:04:34 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 'dict' object is not callable]
INFO : [26/Aug/2023 11:05:26 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:05:26 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 'dict' object is not callable]
INFO : [26/Aug/2023 11:06:15 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:06:15 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 'dict' object is not callable]
INFO : [26/Aug/2023 11:07:25 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:07:25 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 'dict' object is not callable]
INFO : [26/Aug/2023 11:07:54 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:07:54 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : save() missing 1 required positional argument: 'dto']
INFO : [26/Aug/2023 11:08:14 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 11:08:14 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : save() missing 1 required positional argument: 'self']
INFO : [26/Aug/2023 11:08:31 package : micro_auth_service.controller.otpController --> position : OtpController.post]
INFO : [26/Aug/2023 11:09:18 package : micro_auth_service.controller.otpController --> position : OtpController.post]
INFO : [26/Aug/2023 11:09:38 package : micro_auth_service.controller.otpController --> position : OtpController.post]
INFO : [26/Aug/2023 11:13:34 package : micro_auth_service.controller.otpController --> position : OtpController.post]
INFO : [26/Aug/2023 11:34:20 package : micro_auth_service.controller.loginController --> position : Login.post]
INFO : [26/Aug/2023 12:09:29 package : micro_auth_service.controller.loginController --> position : Login.post]
INFO : [26/Aug/2023 12:10:51 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 12:10:51 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 1 validation error for OtpDTO
user_type
  Field required [type=missing, input_value={'email': 'utsavchatterje...m', 'usertype': 'admin'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.2/v/missing]
INFO : [26/Aug/2023 12:11:19 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 12:11:21 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : 'OtpDTO' object has no attribute 'verifiable_cred']
INFO : [26/Aug/2023 12:12:32 package : micro_auth_service.controller.otpController --> position : OtpController.post]
ERROR : [26/Aug/2023 12:12:35 package : micro_auth_service.controller.otpController --> position : OtpController.post --> exception : sent() missing 1 required positional argument: 'dto']
INFO : [26/Aug/2023 12:13:04 package : micro_auth_service.controller.otpController --> position : OtpController.post]
INFO : [26/Aug/2023 12:13:44 package : micro_auth_service.controller.otpController --> position : OtpController.post]
